sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_5435926a6725_key -iv $encrypted_5435926a6725_iv -in service_account.json.enc -out service_account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --file-key service-account.json
