sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_5435926a6725_key -iv $encrypted_5435926a6725_iv -in service_account.json.enc -out service_account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --file-key service_account.json.enc
  - gcloud config set project multi-8s
  - gcloud config set compute/zone australia-southeast1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t rhys117/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rhys117/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
