apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector: # Targets pods with below labels
    component: web
  ports:
    - port: 3000
      targetPort: 3000